### ISSUE TITLE
Docker Compose Error: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1524462744/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by Snake883** [graham-walker/youtube-dl-react-viewer#27]
I'm trying to install/configure via docker compose.

When I run compose up, I get this error message:
`failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1524462744/Dockerfile: no such file or directory`

This is my docker-compose.yml file:

```
version: "2.4"
services:

    db:
        image: mongo:6.0-jammy
        restart: unless-stopped
        mem_limit: 512m
        networks:
            - ytrv_net
        volumes:
            - ytrv_db:/data/db

    app:
        build: .
        image: graham-walker/youtube-dl-react-viewer:1.3.1
        restart: unless-stopped
        mem_limit: 512m
        networks:
            - ytrv_net
        ports:
            - "0.0.0.0:5000:5000/tcp"
        volumes:
            - /mnt/user/MyTube:/youtube-dl
        depends_on:
            - db
        environment:
            - SUPERUSER_USERNAME=admin
            - SUPERUSER_PASSWORD=admin
            - JWT_TOKEN_SECRET=<my secret)
            - SECURE_COOKIES=false
            - YOUTUBE_DL_UPDATE_COMMAND=python3 -m pip install --no-deps -U yt-dlp

volumes:
    ytrv_db:
    ytrv_downloads:

networks:
    default:
    ytrv_net:
        driver: "bridge"

```
